version: "3"

services:
  #MongoDB
  mongo_db:
    volumes:
      - mongo_db:/data/db

  app:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development

volumes:
  mongo_db: {}
